/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Analyze a bucket of same-language files. `files_json` is a JSON object of
 * relative path -> source text. Returns a JSON `{ nodes, edges, errors }`.
 */
export declare function analyze(
  grammar: string,
  querySrc: string,
  importStyle: string,
  filesJson: string,
): string;
